#!/usr/bin/env node
/**
 * Atlas Open PR — Weekly Review Issue Creator
 *
 * Reads pulse.json + decision.json, formats a structured weekly review,
 * and opens a GitHub Issue (used as the review dashboard).
 *
 * Usage: node scripts/atlas/open_pr.js /tmp/pulse.json /tmp/decision.json
 *
 * Required env:
 *   GITHUB_TOKEN  — for creating issues
 *   GITHUB_REPOSITORY — set automatically by GitHub Actions (owner/repo)
 */

const https = require('https');
const fs = require('fs');

const [,, pulsePath, decisionPath] = process.argv;

if (!pulsePath) {
  process.stderr.write('Usage: node open_pr.js <pulse.json> [decision.json]\n');
  process.exit(1);
}

const pulse = JSON.parse(fs.readFileSync(pulsePath, 'utf8'));
const decision = decisionPath && fs.existsSync(decisionPath)
  ? JSON.parse(fs.readFileSync(decisionPath, 'utf8'))
  : null;

// ─── Format issue body ────────────────────────────────────────────────────────

function formatMrr(v) {
  if (v == null) return 'N/A';
  return `$${Number(v).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 0 })}`;
}

function formatDelta(v) {
  if (v == null) return '';
  const sign = v > 0 ? '+' : '';
  return ` (${sign}${v}% WoW)`;
}

function anomalyIcon(type) {
  return type === 'OPPORTUNITY' ? '🟢' : type === 'THREAT' ? '🔴' : '🟡';
}

function buildBody(pulse, decision) {
  const s = pulse.metrics?.stripe;
  const u = pulse.metrics?.uptime;
  const e = pulse.metrics?.sentry;
  const anomalies = pulse.anomalies || [];
  const gaps = pulse.data_gaps || [];
  const score = pulse.sovereign_score;
  const date = new Date(pulse.timestamp).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric'
  });

  let body = `# 📊 Atlas Weekly Review — Week ${pulse.week_index}\n\n`;
  body += `**Date:** ${date}\n`;
  if (score != null) body += `**Sovereign Score:** ${score}/100\n`;
  body += `\n---\n\n`;

  // Metrics
  body += `## 📈 Metrics\n\n`;
  body += `| Metric | Value |\n|--------|-------|\n`;

  if (s?.available) {
    body += `| MRR | ${formatMrr(s.mrr)}${formatDelta(pulse.deltas?.mrr)} |\n`;
    body += `| Customers | ${s.customer_count} |\n`;
    body += `| New MRR (7d) | ${formatMrr(s.new_mrr_7d)} |\n`;
    body += `| Churned MRR (7d) | ${formatMrr(s.churned_mrr_7d)} |\n`;
  } else {
    body += `| MRR | ⚠️ ${s?.reason || 'Stripe not configured'} |\n`;
  }

  if (u?.available) {
    body += `| Uptime (7d) | ${u.all_up ? '✅ All monitors up' : '🔴 Incident detected'} |\n`;
    body += `| Lowest uptime | ${u.lowest_uptime_7d}% |\n`;
  }

  if (e?.available) {
    body += `| Unresolved errors | ${e.unresolved_issues} |\n`;
    if (e.top_error) {
      body += `| Top error | \`${e.top_error.title?.substring(0, 60)}\` (${e.top_error.count} events) |\n`;
    }
  }

  body += `\n`;

  // Anomalies
  if (anomalies.length > 0) {
    body += `## 🔍 Anomalies Detected\n\n`;
    anomalies.forEach(a => {
      body += `- ${anomalyIcon(a.type)} **${a.type}** (${a.metric}): ${a.message}\n`;
    });
    body += `\n`;
  }

  // Decision
  if (decision) {
    body += `## 🎯 This Week's Action\n\n`;
    body += `**Action:** \`${decision.action}\`\n`;
    body += `**Agent:** ${decision.agent}\n`;
    body += `**Confidence:** ${decision.confidence}\n`;
    body += `**Reasoning:** ${decision.reasoning}\n`;
    body += `**Expected impact:** ${decision.estimated_impact}\n`;
    body += `\n`;
  }

  // Data gaps
  if (gaps.length > 0) {
    body += `## ⚠️ Data Gaps\n\n`;
    body += `The following metrics are unavailable. Run \`/atlas diag\` to configure:\n\n`;
    gaps.forEach(g => {
      body += `- **${g.source}**: ${g.reason}\n`;
    });
    body += `\n`;
  }

  // Weekly review checklist
  body += `## ✅ 15-Minute Review Checklist\n\n`;
  body += `Complete this before closing the issue:\n\n`;
  body += `- [ ] Revenue: MRR trend reviewed\n`;
  body += `- [ ] Activation: funnel drop-off checked\n`;
  body += `- [ ] Errors: Sentry top issues reviewed\n`;
  body += `- [ ] Support: inbox cleared or triaged\n`;
  body += `- [ ] Decision: \`YOUR_NEXT_ACTION.md\` updated with one specific action\n`;

  body += `\n---\n*Generated by Atlas Growth Engine — Week ${pulse.week_index}*\n`;

  return body;
}

// ─── Create GitHub Issue ──────────────────────────────────────────────────────

async function createIssue(title, body) {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPOSITORY;

  if (!token || !repo) {
    process.stderr.write('[open_pr] GITHUB_TOKEN or GITHUB_REPOSITORY not set — printing to stdout\n');
    process.stdout.write(`\n${title}\n\n${body}\n`);
    return;
  }

  const [owner, repoName] = repo.split('/');
  const payload = JSON.stringify({
    title,
    body,
    labels: ['atlas-review'],
  });

  return new Promise((resolve, reject) => {
    const req = https.request({
      hostname: 'api.github.com',
      path: `/repos/${owner}/${repoName}/issues`,
      method: 'POST',
      headers: {
        'Authorization': `token ${token}`,
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(payload),
        'User-Agent': 'atlas-growth-engine',
        'Accept': 'application/vnd.github.v3+json',
      },
    }, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        if (res.statusCode === 201) {
          const issue = JSON.parse(data);
          process.stderr.write(`[open_pr] Issue created: ${issue.html_url}\n`);
          resolve(issue);
        } else {
          process.stderr.write(`[open_pr] GitHub API error ${res.statusCode}: ${data}\n`);
          reject(new Error(`GitHub API error ${res.statusCode}`));
        }
      });
    });
    req.on('error', reject);
    req.write(payload);
    req.end();
  });
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const weekNum = pulse.week_index;
  const dateStr = new Date(pulse.timestamp).toISOString().split('T')[0];
  const hasCritical = (pulse.anomalies || []).some(a => a.severity === 'critical');

  const emoji = hasCritical ? '🚨' : '📊';
  const title = `${emoji} Atlas Weekly Review — Week ${weekNum} (${dateStr})`;
  const body = buildBody(pulse, decision);

  await createIssue(title, body);
}

main().catch(err => {
  process.stderr.write(`[open_pr] Fatal: ${err.message}\n`);
  process.exit(1);
});
